### ISSUE TITLE
Project Outline: Overview Section

### ISSUE THREAD

**Issue by jameslyleyoung** [CoderGirlminion/liftoff-assignments#1]
Really all this section needs to do is answer three questions.
1.  What does your app do?
2.  What will users find useful about your app.
3.  What was your inspiration(s) for building this app.

**Comment by CoderGirlminion** [comment]
1. What does your app do?
It provides a visual demonstration that different protein forms can come from one gene.  One gene may process several various transcriptions messages in which each transcripts will genetically code for a specific protein.

2.What will users find useful about your app?
It is a text book diagram regarding genetic transcriptions into different proteins from one protein.  

3. What was the inspiration for building this app?
I enjoy genetics.
